name: Spec Creator
description: Creates a spec

inputs:
  version: # id of input
    description: The version to insert into the spec
    required: true
  spec:
    description: Spec file to use to generate GCloud specs
    required: true
outputs:
  time: # id of output
    description: The time we greeted you

runs:
  using: node24
  main: dist/index.js
